### JPG
GET {{HOST}}/convert?
    url=https://media.githubusercontent.com/media/genesis-city/parcels/new-client-images/maps/lod-0/3/0%2C1.jpg

### GIF
GET {{HOST}}/convert?
    url=https://media2.giphy.com/media/tFSqMSMnzPRTAdvKyr/200w.gif?cid=6c09b9525drl2zrqbnoxwimzgz46j9krcofh2hyqu9tlay4t%26ep=v1_gifs_search%26rid=200w.gif%26ct=g

### GIF Wait
GET {{HOST}}/convert?
    waitForCompletion=true&
    url=https://media2.giphy.com/media/tFSqMSMnzPRTAdvKyr/200w.gif?cid=6c09b9525drl2zrqbnoxwimzgz46j9krcofh2hyqu9tlay4t%26ep=v1_gifs_search%26rid=200w.gif%26ct=g

### WEBP (Animated)
GET {{HOST}}/convert?
    url=https://i.seadn.io/gae/Jfty-cj_9VSeSn_l8OYxyuEefVL-slOoa-jYpv2FlnK-S8mD2V0bZlTIMOQT5KEJhIxqxzPQbTqfpRogGU7hqqDT7NR9-If0iMhoAQ?w=500&
    auto=format
